name: Build Docker Image

on:
  push:
    paths:
      - 'uday-app/**'  # Caminho para o diretório do aplicativo Flask
    branches:
      - main  # Branch principal

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir versão da imagem
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker com tags
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uday-app:${IMAGE_TAG} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/uday-app:${IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/uday-app:latest

      - name: Push da imagem com tag única e latest
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uday-app:${IMAGE_TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uday-app:latest
